[package]
name = "pure_lang_binary_proc_macros"
edition = "2024"
version.workspace = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
proc-macro-crate = "3.3.0"

[lib]
proc-macro = true